@W-15006946 - Release v1.12.0
SalesforceCommerceCloud/commerce-sdk-isomorphic pull request #145
Opened 2024-03-04 19:01 UTC by alexvuong

Added Shopper SEO APIs

2024-03-04 19:28 UTC, joeluong-sfcc requested changes

2024-03-04 19:28 UTC, joeluong-sfcc commented on apis/shopper-products/shopper-products.raml
> +            type: string
See same comment on `commerce-sdk`: https://github.com/SalesforceCommerceCloud/commerce-sdk/pull/399#pullrequestreview-1915149540

2024-03-04 22:43 UTC, alexvuong commented on apis/shopper-products/shopper-products.raml
> +            type: string
Made changes as suggested

2024-03-05 15:48 UTC, joeluong-sfcc approved these changes

2024-03-05 20:00 UTC, bendvc approved these changes

2024-03-05 20:28 UTC, merged