Don't set user-agent in browser because it will fail.
SalesforceCommerceCloud/commerce-sdk-isomorphic pull request #85
Opened 2022-04-14 18:54 UTC by wjhsf

It fails noisily, and that's scary! 🤫

2022-04-14 19:32 UTC, unandyala requested changes

2022-04-14 19:32 UTC, unandyala commented on src/static/helpers/environment.ts
> + * Copyright (c) 2022, salesforce.com, inc.
I believe the copyright now should have Salesforce, Inc.

2022-04-18 17:21 UTC, tarcang approved these changes

2022-04-19 16:11 UTC, joeluong-sfcc approved these changes

2022-04-20 18:32 UTC, unandyala approved these changes

2022-04-22 17:17 UTC, merged